#! /usr/bin/python

import fileinput

import argparse

parser = argparse.ArgumentParser(description="Count yes/no responses to stimuli.")

parser.add_argument("files", metavar="FILE", nargs="*", help="input files. stdin is used if no files are given.")
args = parser.parse_args()

data = {}

for line in fileinput.input(files=args.files if len(args.files) > 0  else ('-',) ):
  tokens = line.split()
  try:
    x = float(tokens[0])
    if not x in data:
      data[x] = {'yes' : 0, 'total' : 0 }
    c = 1
    if len(tokens) > 1:
      c = int(tokens[1])
    data[x]['yes'] += c
    data[x]['total'] += 1
  except:
    pass

for k in data:
  print(k,data[k]['yes'],data[k]['total'])
