#! /usr/bin/python

import fileinput

delim=' '
sum = []
for line in fileinput.input():
  fields = line.split(delim)
  for i in range(len(fields)):
    try:
      x = float(fields[i])
      if i == len(sum):
        sum.append(0)

      sum[i] += x

    except:
      pass

line = ""
for i in range(len(sum)):
  line += " " + str(sum[i])
print line.strip()
