#! /usr/bin/python

import fileinput, math

delim=' '
avg= []
sum = []
num = []
for line in fileinput.input():
  fields = line.split(delim)
  for i in range(len(fields)):
    try:
      x = float(fields[i])
      if i == len(avg):
        avg.append(0)
      if i == len(sum):
        sum.append(0)
      if i == len(num):
        num.append(0)

      num[i] += 1
      delta = x - avg[i]
      avg[i] += delta/num[i]
      delta2 = x - avg[i]
      sum[i] += delta*delta2
    except:
      pass

line = ""
for i in range(len(sum)):
  if num[i] < 2:
    line += "nan"
  else:
    line += " " + str(math.sqrt(sum[i]/(num[i]-1))/math.sqrt(num[i]))
print line.strip()
